# Generated by Django 5.1.15 on 2026-06-23 13:13

import apps.users.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0003_laboratory"),
        ("users", "0003_access_scope"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.users.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="userprofile",
            name="laboratory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_profiles",
                to="scheduling.laboratory",
                verbose_name="Лаборатория",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="training_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_profiles",
                to="scheduling.trainingcenter",
                verbose_name="Учебный центр",
            ),
        ),
    ]
