# Generated by Django 5.1.15 on 2026-06-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_lab_work_capacity"),
        ("scheduling", "0003_laboratory"),
    ]

    operations = [
        migrations.AddField(
            model_name="discipline",
            name="laboratories",
            field=models.ManyToManyField(
                blank=True,
                related_name="disciplines",
                to="scheduling.laboratory",
                verbose_name="Лаборатории",
            ),
        ),
        migrations.AddField(
            model_name="labwork",
            name="laboratories",
            field=models.ManyToManyField(
                blank=True,
                related_name="lab_works",
                to="scheduling.laboratory",
                verbose_name="Лаборатории",
            ),
        ),
        migrations.AlterField(
            model_name="discipline",
            name="training_centers",
            field=models.ManyToManyField(
                blank=True,
                related_name="disciplines",
                to="scheduling.trainingcenter",
                verbose_name="Учебные центры",
            ),
        ),
        migrations.AlterField(
            model_name="labwork",
            name="training_centers",
            field=models.ManyToManyField(
                blank=True,
                related_name="lab_works",
                to="scheduling.trainingcenter",
                verbose_name="Учебные центры",
            ),
        ),
    ]
