from collections import Counter, defaultdict

from django.db import migrations, models


DISCIPLINES_M2M_TABLE = "academics_labwork_disciplines"
LABWORK_TABLE = "academics_labwork"


def _table_exists(schema_editor, table_name: str) -> bool:
    return table_name in schema_editor.connection.introspection.table_names()


def _column_exists(schema_editor, table_name: str, column_name: str) -> bool:
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT EXISTS (
                SELECT 1
                FROM information_schema.columns
                WHERE table_name = %s AND column_name = %s
            )
            """,
            [table_name, column_name],
        )
        return bool(cursor.fetchone()[0])


def ensure_disciplines_m2m_table(apps, schema_editor):
    if _table_exists(schema_editor, DISCIPLINES_M2M_TABLE):
        return
    schema_editor.execute(
        f"""
        CREATE TABLE {DISCIPLINES_M2M_TABLE} (
            id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            labwork_id bigint NOT NULL
                REFERENCES {LABWORK_TABLE}(id)
                DEFERRABLE INITIALLY DEFERRED,
            discipline_id bigint NOT NULL
                REFERENCES academics_discipline(id)
                DEFERRABLE INITIALLY DEFERRED,
            CONSTRAINT academics_labwork_disciplines_labwork_id_discipline_id_uniq
                UNIQUE (labwork_id, discipline_id)
        )
        """
    )
    schema_editor.execute(
        f"CREATE INDEX academics_labwork_disciplines_labwork_id_idx "
        f"ON {DISCIPLINES_M2M_TABLE} (labwork_id)"
    )
    schema_editor.execute(
        f"CREATE INDEX academics_labwork_disciplines_discipline_id_idx "
        f"ON {DISCIPLINES_M2M_TABLE} (discipline_id)"
    )


def migrate_discipline_to_m2m(apps, schema_editor):
    if not _column_exists(schema_editor, LABWORK_TABLE, "discipline_id"):
        return
    LabWork = apps.get_model("academics", "LabWork")
    for lab_work in LabWork.objects.exclude(discipline_id__isnull=True).iterator():
        if not lab_work.disciplines.filter(pk=lab_work.discipline_id).exists():
            lab_work.disciplines.add(lab_work.discipline_id)


def _lab_signature(lab_work) -> tuple:
    lab_ids = tuple(sorted(lab_work.laboratories.values_list("pk", flat=True)))
    return (
        lab_work.title.strip().lower(),
        lab_work.default_room_id,
        lab_work.primary_stand_id,
        lab_ids,
    )


def _activity_score(lab_work, Booking, LabSession, StudentGroup) -> int:
    return (
        LabSession.objects.filter(lab_work_id=lab_work.pk).count()
        + Booking.objects.filter(lab_work_id=lab_work.pk).count()
        + StudentGroup.objects.filter(lab_works=lab_work.pk).count()
    )


def merge_duplicate_lab_works(apps, schema_editor):
    LabWork = apps.get_model("academics", "LabWork")
    Booking = apps.get_model("bookings", "Booking")
    LabSession = apps.get_model("scheduling", "LabSession")
    ScheduleEntry = apps.get_model("scheduling", "ScheduleEntry")
    StudentGroup = apps.get_model("academics", "StudentGroup")

    groups: dict[tuple, list] = defaultdict(list)
    for lab_work in LabWork.objects.prefetch_related("laboratories").iterator(chunk_size=500):
        groups[_lab_signature(lab_work)].append(lab_work)

    for duplicates in groups.values():
        if len(duplicates) < 2:
            continue
        canonical = max(
            duplicates,
            key=lambda lw: _activity_score(lw, Booking, LabSession, StudentGroup),
        )
        duplicate_ids = [lw.pk for lw in duplicates if lw.pk != canonical.pk]
        if not duplicate_ids:
            continue

        durations = [lw.duration_minutes for lw in duplicates]
        canonical.duration_minutes = Counter(durations).most_common(1)[0][0]
        canonical.save(update_fields=["duration_minutes"])

        for duplicate in duplicates:
            if duplicate.pk == canonical.pk:
                continue
            canonical.disciplines.add(*duplicate.disciplines.values_list("pk", flat=True))
            canonical.student_groups.add(*duplicate.student_groups.values_list("pk", flat=True))
            canonical.laboratories.add(*duplicate.laboratories.values_list("pk", flat=True))
            canonical.training_centers.add(*duplicate.training_centers.values_list("pk", flat=True))

            LabSession.objects.filter(lab_work_id=duplicate.pk).update(lab_work_id=canonical.pk)
            Booking.objects.filter(lab_work_id=duplicate.pk).update(lab_work_id=canonical.pk)
            ScheduleEntry.objects.filter(lab_work_id=duplicate.pk).update(lab_work_id=canonical.pk)

        LabWork.objects.filter(pk__in=duplicate_ids).delete()


def drop_labwork_discipline_number_unique(apps, schema_editor):
    quote_name = schema_editor.connection.ops.quote_name
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT c.conname
            FROM pg_constraint c
            JOIN pg_class t ON c.conrelid = t.oid
            WHERE t.relname = %s
              AND c.contype = 'u'
              AND pg_get_constraintdef(c.oid) LIKE %s
            """,
            [LABWORK_TABLE, "%discipline_id%"],
        )
        constraint_names = [row[0] for row in cursor.fetchall()]
    for constraint_name in constraint_names:
        schema_editor.execute(
            f"ALTER TABLE {quote_name(LABWORK_TABLE)} "
            f"DROP CONSTRAINT IF EXISTS {quote_name(constraint_name)}"
        )


def drop_labwork_discipline_column(apps, schema_editor):
    if not _column_exists(schema_editor, LABWORK_TABLE, "discipline_id"):
        return
    schema_editor.execute(
        f"ALTER TABLE {LABWORK_TABLE} DROP COLUMN discipline_id CASCADE"
    )


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("academics", "0008_department"),
        ("bookings", "0001_initial"),
        ("scheduling", "0005_schedule_duration_constraints"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    ensure_disciplines_m2m_table,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="labwork",
                    name="disciplines",
                    field=models.ManyToManyField(
                        related_name="lab_works",
                        to="academics.discipline",
                        verbose_name="Дисциплины",
                    ),
                ),
            ],
        ),
        migrations.RunPython(migrate_discipline_to_m2m, migrations.RunPython.noop),
        migrations.RunPython(merge_duplicate_lab_works, migrations.RunPython.noop),
        migrations.RunPython(
            drop_labwork_discipline_number_unique,
            migrations.RunPython.noop,
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    drop_labwork_discipline_column,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name="labwork",
                    unique_together=set(),
                ),
                migrations.RemoveField(
                    model_name="labwork",
                    name="discipline",
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="labwork",
            options={
                "ordering": ["number", "title"],
                "verbose_name": "Лабораторная работа",
                "verbose_name_plural": "Лабораторные работы",
            },
        ),
    ]
