from django.urls import path

from apps.bookings.views.lab_head import (
    LabHeadBindingsView,
    LabHeadDisciplineBindView,
    LabHeadDisciplineCreateView,
    LabHeadDisciplineUnbindView,
    LabHeadHomeView,
    LabHeadLabWorkBindView,
    LabHeadLabWorkCreateView,
    LabHeadLabWorkUnbindView,
    LabHeadLabWorkUpdateView,
    LabHeadLabWorksView,
    LabHeadPersonBindingsView,
    LabHeadPersonCreateView,
    LabHeadPeopleView,
    LabHeadRoomUpdateView,
    LabHeadRoomsView,
    LabHeadScheduleCreateView,
    LabHeadScheduleView,
    LabHeadStandCreateView,
    LabHeadStandsView,
)
from apps.bookings.views.staff import (
    StaffDisciplinesView,
    StaffLabWorksView,
    StaffLabWorkUploadView,
    StaffPeopleView,
    StaffReportDownloadView,
    StaffReportsView,
    StaffRoomsView,
    StaffScheduleView,
    StaffStandCreateView,
    StaffStandsView,
    StaffSupportReplyView,
    StaffSupportView,
)
from apps.bookings.views.web import (
    BookFilterPartialView,
    BookLabWorkWebView,
    BookingDetailWebView,
    CancelBookingWebView,
    DisciplineListWebView,
    HomeView,
    LabWorkListWebView,
    MyBookingsWebView,
    PatchNotesWebView,
    StaffBookingsWebView,
    StaffManualBookingWebView,
    StaffManualFilterPartialView,
    StaffManualStudentSearchView,
    StaffStatusUpdateWebView,
    SupportCreateWebView,
    SupportDetailWebView,
    SupportListWebView,
    WaitlistJoinWebView,
)

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("disciplines/", DisciplineListWebView.as_view(), name="disciplines"),
    path(
        "disciplines/<int:discipline_id>/lab-works/",
        LabWorkListWebView.as_view(),
        name="lab-works",
    ),
    path("lab-works/<int:lab_work_id>/book/", BookLabWorkWebView.as_view(), name="book-lab-work"),
    path(
        "lab-works/<int:lab_work_id>/book/filter/",
        BookFilterPartialView.as_view(),
        name="book-filter",
    ),
    path("waitlist/join/", WaitlistJoinWebView.as_view(), name="waitlist-join"),
    path("my-bookings/", MyBookingsWebView.as_view(), name="my-bookings"),
    path("my-bookings/<int:pk>/", BookingDetailWebView.as_view(), name="booking-detail"),
    path("my-bookings/<int:pk>/cancel/", CancelBookingWebView.as_view(), name="cancel-booking"),
    path("patch-notes/", PatchNotesWebView.as_view(), name="patch-notes"),
    path("support/", SupportListWebView.as_view(), name="support"),
    path("support/create/", SupportCreateWebView.as_view(), name="support-create"),
    path("support/<int:pk>/", SupportDetailWebView.as_view(), name="support-detail"),
    path("staff/bookings/", StaffBookingsWebView.as_view(), name="staff-bookings"),
    path(
        "staff/bookings/manual/",
        StaffManualBookingWebView.as_view(),
        name="staff-booking-manual",
    ),
    path(
        "staff/bookings/manual/search/",
        StaffManualStudentSearchView.as_view(),
        name="staff-manual-student-search",
    ),
    path(
        "staff/bookings/manual/filter/<int:lab_work_id>/",
        StaffManualFilterPartialView.as_view(),
        name="staff-manual-filter",
    ),
    path(
        "staff/bookings/<int:pk>/status/",
        StaffStatusUpdateWebView.as_view(),
        name="staff-booking-status",
    ),
    path("staff/disciplines/", StaffDisciplinesView.as_view(), name="staff-disciplines"),
    path("staff/lab-works/", StaffLabWorksView.as_view(), name="staff-lab-works"),
    path(
        "staff/lab-works/<int:pk>/upload/",
        StaffLabWorkUploadView.as_view(),
        name="staff-lab-work-upload",
    ),
    path("staff/stands/", StaffStandsView.as_view(), name="staff-stands"),
    path("staff/rooms/", StaffRoomsView.as_view(), name="staff-rooms"),
    path("staff/stands/create/", StaffStandCreateView.as_view(), name="staff-stand-create"),
    path("staff/schedule/", StaffScheduleView.as_view(), name="staff-schedule"),
    path("staff/people/", StaffPeopleView.as_view(), name="staff-people"),
    path("staff/support/", StaffSupportView.as_view(), name="staff-support"),
    path("staff/support/<int:pk>/reply/", StaffSupportReplyView.as_view(), name="staff-support-reply"),
    path("staff/reports/", StaffReportsView.as_view(), name="staff-reports"),
    path(
        "staff/reports/<str:report_type>/download/",
        StaffReportDownloadView.as_view(),
        name="staff-report-download",
    ),
    path("lab-head/", LabHeadHomeView.as_view(), name="lab-head-home"),
    path("lab-head/people/", LabHeadPeopleView.as_view(), name="lab-head-people"),
    path("lab-head/people/create/", LabHeadPersonCreateView.as_view(), name="lab-head-person-create"),
    path(
        "lab-head/people/<int:pk>/bindings/",
        LabHeadPersonBindingsView.as_view(),
        name="lab-head-person-bindings",
    ),
    path("lab-head/bindings/", LabHeadBindingsView.as_view(), name="lab-head-bindings"),
    path(
        "lab-head/bindings/disciplines/create/",
        LabHeadDisciplineCreateView.as_view(),
        name="lab-head-discipline-create",
    ),
    path(
        "lab-head/bindings/disciplines/<int:pk>/bind/",
        LabHeadDisciplineBindView.as_view(),
        name="lab-head-discipline-bind",
    ),
    path(
        "lab-head/bindings/disciplines/<int:pk>/unbind/",
        LabHeadDisciplineUnbindView.as_view(),
        name="lab-head-discipline-unbind",
    ),
    path(
        "lab-head/bindings/lab-works/<int:pk>/bind/",
        LabHeadLabWorkBindView.as_view(),
        name="lab-head-lab-work-bind",
    ),
    path(
        "lab-head/bindings/lab-works/<int:pk>/unbind/",
        LabHeadLabWorkUnbindView.as_view(),
        name="lab-head-lab-work-unbind",
    ),
    path("lab-head/lab-works/", LabHeadLabWorksView.as_view(), name="lab-head-lab-works"),
    path(
        "lab-head/lab-works/create/",
        LabHeadLabWorkCreateView.as_view(),
        name="lab-head-lab-work-create",
    ),
    path(
        "lab-head/lab-works/<int:pk>/update/",
        LabHeadLabWorkUpdateView.as_view(),
        name="lab-head-lab-work-update",
    ),
    path("lab-head/rooms/", LabHeadRoomsView.as_view(), name="lab-head-rooms"),
    path("lab-head/rooms/<int:pk>/update/", LabHeadRoomUpdateView.as_view(), name="lab-head-room-update"),
    path("lab-head/stands/", LabHeadStandsView.as_view(), name="lab-head-stands"),
    path("lab-head/stands/create/", LabHeadStandCreateView.as_view(), name="lab-head-stand-create"),
    path("lab-head/schedule/", LabHeadScheduleView.as_view(), name="lab-head-schedule"),
    path(
        "lab-head/schedule/create/",
        LabHeadScheduleCreateView.as_view(),
        name="lab-head-schedule-create",
    ),
]
