# Generated by Django 5.1.15 on 2026-06-23 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0002_plan_features"),
    ]

    operations = [
        migrations.CreateModel(
            name="Laboratory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Название")),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Краткое название"
                    ),
                ),
            ],
            options={
                "verbose_name": "Лаборатория",
                "verbose_name_plural": "Лаборатории",
                "ordering": ["training_center", "name"],
            },
        ),
        migrations.RenameIndex(
            model_name="labsession",
            new_name="scheduling__starts__6296ba_idx",
            old_name="scheduling__starts__a5f2c1_idx",
        ),
        migrations.RenameIndex(
            model_name="labsession",
            new_name="scheduling__lab_wor_0a1371_idx",
            old_name="scheduling__lab_wor_91ab42_idx",
        ),
        migrations.AddField(
            model_name="laboratory",
            name="training_center",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="laboratories",
                to="scheduling.trainingcenter",
                verbose_name="Учебный центр",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="laboratory",
            unique_together={("training_center", "name")},
        ),
    ]
